---
{
  "kind": "pipeline",
  "name": "Kubernetes",
  "node_selector": { "drone": true },
  "platform": { "arch": "amd64", "os": "linux" },
  "steps":
    [
      {
        "commands":
          [
            "npm install prettier",
            "echo .pre-commit-config.yaml >> .prettierignore",
            'npx prettier --check "**/*.{ts,js,md,yaml,yml,sass,css,scss,html,htm}"',
          ],
        "image": "node:lts-buster",
        "name": "Prettier lint",
        "pull": "always",
      },
      {
        "commands":
          [
            "curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin",
            "golangci-lint run -v --timeout 10m",
          ],
        "image": "golang:1.16-buster",
        "name": "Go lint",
        "pull": "always",
      },
      {
        "commands": ["go test ./..."],
        "image": "golang:1.16-buster",
        "name": "Go test",
        "pull": "always",
      },
      {
        "commands":
          [
            "go get github.com/mitchellh/gox",
            'gox -osarch "!darwin/386" -output="dist/{{.Dir}}_{{.OS}}_{{.Arch}}"',
          ],
        "image": "golang:1.16-buster",
        "name": "Go build",
        "pull": "always",
      },
    ],
  "type": "kubernetes",
}
